"""Shared state definition for the CodeRAG LangGraph reasoning agent."""

from typing import TypedDict, Optional


class AgentState(TypedDict):
    """State object that flows through every node in the reasoning graph.

    Each node receives the full state and returns a partial dict
    containing only the fields it updates — LangGraph merges automatically.
    """

    query: str                        # the user's original question
    repo_id: str                      # which repo to search
    retrieval_context: Optional[dict] # output of retrieve_context()
    hypothesis: Optional[str]         # generated by Analyze node
    hypothesis_history: list[str]     # all hypotheses across iterations
    confidence: float                 # 0.0 to 1.0, set by Verify node
    iteration: int                    # loop counter, max 3
    evidence: list[dict]              # supporting code chunks
    root_cause: Optional[str]         # finalized by Respond node
    suggested_fix: Optional[str]      # finalized by Respond node
    error: Optional[str]              # populated if anything fails
    final_response: Optional[dict]    # the complete structured output


def initial_state(query: str, repo_id: str) -> AgentState:
    """Returns a clean initial AgentState for a new agent run."""
    return AgentState(
        query=query,
        repo_id=repo_id,
        retrieval_context=None,
        hypothesis=None,
        hypothesis_history=[],
        confidence=0.0,
        iteration=0,
        evidence=[],
        root_cause=None,
        suggested_fix=None,
        error=None,
        final_response=None,
    )
